/**
 * The three currencies of a turn.
 *
 * ACC is money and lives on the Firm. The other two live here:
 *  - Time: founder hours. Does NOT roll over. This is what makes a turn a choice.
 *  - Relationship capital (RC): earned by delivering on time, spent on introductions,
 *    queue jumps and first looks. Carries between pulses but decays.
 */

import type { KnowledgeEffect, TurnBudget } from "./types.ts";

/** Founder hours in a week. */
export const BASE_TIME_PER_PULSE = 40;
/** Relationship capital generated by simply operating. */
export const BASE_RC_PER_PULSE = 12;
/** Carried RC decays each pulse, so hoarding it is not a strategy. */
export const RC_DECAY = 0.04;
export const RC_CAP = 240;

function sumEffect(effects: KnowledgeEffect[], kind: "time_income" | "rc_income"): number {
  let total = 0;
  for (const effect of effects) {
    if (effect.kind === kind) total += effect.value;
  }
  return total;
}

export function createBudget(effects: KnowledgeEffect[]): TurnBudget {
  return {
    timeTotal: Math.max(1, Math.round(BASE_TIME_PER_PULSE + sumEffect(effects, "time_income"))),
    timeSpent: 0,
    rcTotal: Math.max(0, Math.round(BASE_RC_PER_PULSE + sumEffect(effects, "rc_income"))),
    rcSpent: 0,
  };
}

/**
 * Start of pulse. Time resets to zero spent every week regardless of what was left,
 * and the totals are recomputed so a knowledge node or a new hire takes effect at once.
 */
export function resetBudget(_budget: TurnBudget, effects: KnowledgeEffect[]): TurnBudget {
  return createBudget(effects);
}

export type SpendResult = { ok: boolean; budget: TurnBudget; reason?: string };

/** Pure. Never mutates the input budget. */
export function spend(budget: TurnBudget, cost: { time?: number; rc?: number }): SpendResult {
  const time = Math.max(0, cost.time ?? 0);
  const rc = Math.max(0, cost.rc ?? 0);
  if (budget.timeSpent + time > budget.timeTotal) {
    return { ok: false, budget, reason: "insufficient_time" };
  }
  if (budget.rcSpent + rc > budget.rcTotal) {
    return { ok: false, budget, reason: "insufficient_relationship_capital" };
  }
  return {
    ok: true,
    budget: {
      ...budget,
      timeSpent: budget.timeSpent + time,
      rcSpent: budget.rcSpent + rc,
    },
  };
}

export function remaining(budget: TurnBudget): { time: number; rc: number } {
  return {
    time: Math.max(0, budget.timeTotal - budget.timeSpent),
    rc: Math.max(0, budget.rcTotal - budget.rcSpent),
  };
}

export function decayRelationshipCapital(carried: number): number {
  if (!Number.isFinite(carried) || carried <= 0) return 0;
  return Math.min(RC_CAP, Math.max(0, carried * (1 - RC_DECAY)));
}

/**
 * On-time deliveries earn. Missed deliveries cost more than an on-time delivery earns,
 * because a reputation is slower to build than to lose.
 */
export function earnRelationshipCapital(
  carried: number,
  events: { onTime: boolean; value: number }[],
): number {
  let total = Number.isFinite(carried) ? carried : 0;
  for (const event of events) {
    const magnitude = Math.max(0, event.value);
    total += event.onTime ? magnitude : -magnitude * 2.5;
  }
  return Math.min(RC_CAP, Math.max(0, total));
}

/** 0..1, how much of the turn's time is gone. The Pulse wheel draws this as an arc. */
export function budgetPressure(budget: TurnBudget): number {
  if (budget.timeTotal <= 0) return 1;
  return Math.min(1, Math.max(0, budget.timeSpent / budget.timeTotal));
}
